# Generated by Django 3.0.7 on 2020-06-18 07:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AustralianStates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('enname', models.CharField(max_length=254)),
                ('locname', models.CharField(max_length=254)),
                ('offname', models.CharField(max_length=254)),
                ('boundary', models.CharField(max_length=254)),
                ('adminlevel', models.IntegerField()),
                ('wikidata', models.CharField(max_length=254)),
                ('wikimedia', models.CharField(max_length=254)),
                ('timestamp', models.CharField(max_length=254)),
                ('note', models.CharField(max_length=254)),
                ('path', models.CharField(max_length=254)),
                ('rpath', models.CharField(max_length=254)),
                ('iso3166_2', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
