# Generated by Django 3.0.7 on 2020-06-18 08:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20200618_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='AustraliaState',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('enname', models.CharField(max_length=254)),
                ('locname', models.CharField(max_length=254)),
                ('offname', models.CharField(max_length=254, null=True)),
                ('boundary', models.CharField(max_length=254)),
                ('adminlevel', models.IntegerField()),
                ('wikidata', models.CharField(max_length=254)),
                ('wikimedia', models.CharField(max_length=254)),
                ('timestamp', models.CharField(max_length=254)),
                ('note', models.CharField(max_length=254, null=True)),
                ('path', models.CharField(max_length=254)),
                ('rpath', models.CharField(max_length=254)),
                ('iso3166_2', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='australianstates',
            name='adminlevel',
        ),
        migrations.RemoveField(
            model_name='australianstates',
            name='boundary',
        ),
        migrations.RemoveField(
            model_name='australianstates',
            name='country',
        ),
        migrations.RemoveField(
            model_name='australianstates',
            name='enname',
        ),
        migrations.RemoveField(
            model_name='australianstates',
            name='iso3166_2',
        ),
        migrations.RemoveField(
            model_name='australianstates',
            name='locname',
        ),
        migrations.RemoveField(
            model_name='australianstates',
            name='note',
        ),
        migrations.RemoveField(
            model_name='australianstates',
            name='offname',
        ),
        migrations.RemoveField(
            model_name='australianstates',
            name='path',
        ),
        migrations.RemoveField(
            model_name='australianstates',
            name='rpath',
        ),
        migrations.RemoveField(
            model_name='australianstates',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='australianstates',
            name='wikidata',
        ),
        migrations.RemoveField(
            model_name='australianstates',
            name='wikimedia',
        ),
        migrations.AddField(
            model_name='australianstates',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='australianstates',
            name='iso_sub',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='australianstates',
            name='totpop_cy',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='australianstates',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='australianstates',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
